version: '3.8'
services:
  app:
    build: .
    ports:
      - '80:3000' 
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db
  db:
    image: 'postgres:13'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'